### ISSUE TITLE
listFormat line overwrites most text to the right

### ISSUE THREAD

**Issue by Jasin2069** [NuSkooler/enigma-bbs#159]
I'm working on a small theme and cannot get the lines to stop at a certain width. This happens with the last callers, who's online, userlist, oneliners. I see this one other enigma bbss as well. 

For example I tried to limit the size on the list format, I'm not sure if that is just for padding
	listFormat: "|00|11{username:<12}|08: |03{oneliner:<40}"

**Expected behavior**
Text to the right is not altered, just like the text to the left
**Actual behavior**
https://imgur.com/a/mJWwI

**Comment by NuSkooler** [comment]
@Jasin2069 You have a couple things to work with:

1. The width of the view itself
2. The format system works similar to Python's format mini language: https://docs.python.org/3/library/string.html#format-specification-mini-language

Note that there is currently a one-off bug in string "precision" that needs addressed at some point. But you can try things like `"|00|11{username:<12.11}"` (see other examples in default `theme.hjson`)

**Comment by Jasin2069** [comment]
I did try using the list format. I even tried <1.1.

It wasn't until I added a width to VM1. I set the width to 20 that it followed the listformat's width. So the 20 for width isn't used but needs to be there.

```
config: {
					listFormat: "|00|11{username:<12}|08: |03{oneliner:<56.55}"
				}
				0: {
					mci: {
						VM1: { height: 10,width: 20 }
```

**Comment by Jasin2069** [comment]
So I've been testing and I really don't need to set the maximum width on the listformat unless it is longer than I want it to be. It's really the width. Doesn't matter what it is set to, it can be 1, 10, 20. It doesn't shorten anything. Setting it to 100 does let it bleed through but even 50 it works fine. 

I'm not quite sure what it is setting however I will be going through my theme and setting a default width of 20. If you would like I can modify your main theme as well and submit a pr. 

Here is an example on your user list https://imgur.com/a/bCf7u

**Comment by NuSkooler** [comment]
@Jasin2069 Thanks for the report. I just looked over this a bit as well. The issue here is views originally tried to auto-scale based on items... I then tacked on `itemFormat` and other more complex drawing which isn't compatible with that idea since the system now only draws as needed.

The real fix here is to remove all the auto-scaling nonsense, probably have each view provide a default width, and finally require themes to set the width explicitly to their liking.

With that said, I'll gladly accept a PR that at least fixes up the `theme.hjson` by setting the widths which will at least mask the issue for 99% of the cases I'm sure. I'll look into this more and get the underlying issues fixed in the future.

**Comment by Jasin2069** [comment]
I added pull #160 for the format. The only thing I can't get working is the bbslist (nothing I change helps) and the main menu rumor since there isn't anything in the theme to modify.

**Comment by NuSkooler** [comment]
The main menu rumor will probably have to wait for another fix on my list that lets theme items set MCI properties that are not in the menu.hjson. Then, you'd be able to set a width for the rumor MCI.

What issue are you seeing on the BBS list?

**Comment by Jasin2069** [comment]
Actually BBS list is fine now when the pull I already did. Maybe I forgot to save/restart it,

**Comment by NuSkooler** [comment]
Created #166 and #167 for full fixes mentioned above.
