### ISSUE TITLE
Add NNTP Support

### ISSUE THREAD

**Issue by coolacid** [NuSkooler/enigma-bbs#184]
Adding NNTP Support would allow remote access to BBS message boards.

This should support read and write and ensure permissions.

**Comment by NuSkooler** [comment]
@coolacid / others: Can you elaborate more on what you're looking for here?

ENiG already supports FTN-style networks so you can get most messages that way. Are there networks that are NNTP only? For things like Usenet, there are some Usenet <> FTN gateway subs available (ie: on fsxNet)

**Comment by streaps** [comment]
I think it's more about reading FTN and BBS message boards with an NNTP client / newsreader. Like https://github.com/ftnapps/jamnntpd

**Comment by NuSkooler** [comment]
[nntp-server](https://github.com/nodeca/nntp-server) looks fairly easy to embed as a content server similar to how Gopher exposes messages.

**Comment by XBessa** [comment]
Integrate JAMNNTPD functionality into Enigma would be awesome

Em dom, 9 de dez de 2018 às 19:07, Bryan Ashby <notifications@github.com>
escreveu:

**Comment by NuSkooler** [comment]
I would not be integrating JamNNTPd as ENiGMA does not support JAM. My understanding is JamNNTPd simply allows access to JAM-backed message bases over NTTP. If _that_ is the goal, it's certainly doable.

What are some popular clients that people use to access BBS message bases over NTTP? I'd like to test against what would be used.

**Comment by XBessa** [comment]
The problem is that a regular NNTP server does not recognize the TO: field,
therefore any echomail written using a NNTP server will be automatically
sent TO:ALL.

JAMNNTPD circumvents this, putting the correct data into the TO: field,
allowing seamless usage of Thunderbird to read echomail, for instance.

JAM is just a detail, its functionality is what matters here.

Em dom, 9 de dez de 2018 às 20:45, Bryan Ashby <notifications@github.com>
escreveu:

**Comment by NuSkooler** [comment]
@XBessa Right. JAM really isn't of any real relevance here.

Serving up content over NNTP in a way that works with BBS style EchoMail is what I'm after -- things like the `TO` field you mention. Do you know of any others? Is there a spec anywhere? I can dig through JamNTTPd, but I'd rather have a spec :)

Sounds like I can use Thunderbird for testing though, so that's good.

**Comment by streaps** [comment]
DFeed is an awsome news reader for the web:

https://github.com/CyberShadow/DFeed
https://forum.dlang.org/

**Comment by NuSkooler** [comment]
OK, here's what I'm currently planning - RFC!
- Similar to the built in Gopher server, +ops can set conf/areas as "publicly" exposed. That is, the confs/areas exposed will be available over NNTP anonymously as **read only**. This would be available for non-secure (NNTP / plain text), and secure (NNTPS / TLS) connections.
- For secure (NNTPS / TLS) connections only: Authenticated users (using your regular username + password) can access confs/areas as per normal ACS rules allow.
- Conference / Area Tags will map to NNTP groups. For example, given a conf tag of "fsxNet" and an area tag of "fsx_bbs", NNTP clients will see "fsxnet.fsx_bbs".

**Comment by NuSkooler** [comment]
Progress update:
![image](https://user-images.githubusercontent.com/1509339/49849326-3e7b7480-fd96-11e8-937c-b5235d2041d8.png)

**Comment by XBessa** [comment]
You can find JAMNNTPD’s source code at

https://github.com/ftnapps/jamnntpd

I have it running at my Mystic system, let me know if you need a test
account

Em seg, 10 de dez de 2018 às 14:44, Bryan Ashby <notifications@github.com>
escreveu:

**Comment by NuSkooler** [comment]
If anyone hook up to Xibalba's groups @ nntp://xibalba.l33t.codes:44514 and report how it's working, it would be appreciated.

**Comment by tracker1** [comment]
Might also be worthwhile to look at Synchronet's NNTP files... Haven't looked, but does Enigma use a globally unique id for messages?  Generally a message on NNTP should be globally unique-ish, so may want to either store the extra field in the DB so the same message doesn't come in twice... serving NNTP should be easy enough.

Also, would probably want to do a crc32 or md5 hash for collisions on message subject+body with front matter, and any signature/tear lines stripped... since there's some risk of potential dupes, but probably less necessary.

**Comment by tracker1** [comment]
Aside, I wrote the logic to check for and add the To field in the DB (NNTP header X-Apparently-To) ... if it's not specified, it will search for the replyto message, and use its' sender as the To field.

**Comment by NuSkooler** [comment]
@tracker1 ENiGMA's NNTP is functional. You can use it and/or read the code here:
https://github.com/NuSkooler/enigma-bbs/blob/0.0.10-alpha/core/servers/content/nntp.js

If there are _specific_ issues, feel free to open them.

**Comment by NuSkooler** [comment]
Read-only NNTP access has been in for a while. Closing this ticket due to inactivity. If write support is desired, please create a new ticket.
