### ISSUE TITLE
Neither Backspace or Delete work in mTCP Telnet

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#412]
Neither the Backspace or Delete key work in mTCP Telnet

**Comment by NuSkooler** [comment]
* CTRL+D is now an additional backspace option by default
* Added CTRL+U as an additional default clear line
* PageUp/PageDown in mTCP Telnet do not send anything desirable, so they will have to do.

**Comment by hollowonepl** [comment]
New comment for old thing. standard MTCP telnet has options to send backspace and enter in various ways, ALT+B and ALT+N before you type your user/password to your fav BBSes in that client sorts above issues without fixing it on the BBS side. There is also a fixed version of MTCP that sends PGUP/DOWN correctly. both issues should be in my humble opinion better fixed in MTCP apps.

**Comment by NuSkooler** [comment]
@hollowonepl Thanks for the info! I plan on doing another full round of telnet client testing sometime fairly soon so this is quite helpful
